<?php
	header('Content-Type: text/xsl');
	header('X-Robots-Tag: noindex, follow', true);
	header('Pragma: public');
	header('Cache-Control: maxage=31536000');
	header('Expires: '.gmdate('D, d M Y H:i:s', time()+31536000).' GMT');
	echo '<?xml version="1.0" encoding="UTF-8"?>'."\n";
?><xsl:stylesheet version="2.0"
		xmlns:html="http://www.w3.org/TR/REC-html40"
		xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
		xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
		xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title>Image Sitemap</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<style>
			body { margin:0; background-color:#efefef; }
			body, table { color:#333333; font-size:11px; font-family:Helvetica, Arial, sans-serif; }
			a { text-decoration:none; color:#777777; }
			a:hover, a:active { text-decoration:underline; color:#d10000; }
			#header { padding:1em; border-bottom:2px solid #555555; margin-bottom:1em; }
			#inner-wrap { padding:0 2em; }
			.description { font-style:italic; margin-bottom:0.5em; }
			table.fancy-table { border-collapse:collapse; border:1px solid #555555; }
			table.fancy-table thead th { border:0 none; border-bottom:1px solid #696969; background-color:#dfdfdf; }
			table.fancy-table tbody tr td { border:0 none; border-top:1px solid #cccccc; }
			table.fancy-table tbody tr:first-child td { border-top:0 none; }
			table.fancy-table th, table.fancy-table td { padding:0.4em 4em 0.4em 1.2em; }
		</style>
	</head>
	<body>
		<div id="wrapper">
			<div id="header">
				<h1 class="page-title">Image Sitemap</h1>
				<div class="description">
					This Image Sitemap was generated by [QS] Image Sitemap Plugin for WordPress, by <a href="http://quadshot.com/">Quadshot</a>.
					For more information about sitemaps in general, you can visit <a href="http://sitemaps.org">sitemaps.org</a>.
				</div>
			</div>
			<div id="inner-wrap">
				<xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &gt; 0">
					<div class="description">
						This Image Sitemap - sitemap index contains [<xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/>] sitemaps.
					</div>
					<table class="fancy-table">
						<thead>
							<tr>
								<th>Sitemap Location</th>
								<th>Last Modified</th>
							</tr>
						</thead>
						<tbody>
							<xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
								<xsl:variable name="location">
									<xsl:value-of select="sitemap:loc"/>
								</xsl:variable>
								<tr>
									<td><a href="{$location}" class="sitemap-link"><xsl:value-of select="sitemap:loc"/></a></td>
									<td><xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)))"/></td>
								</tr>
							</xsl:for-each>
						</tbody>
					</table>
				</xsl:if>
				<xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &lt; 1">
					<div class="description">
						This Image Sitemap - sitemap index contains [<xsl:value-of select="count(sitemap:urlset/sitemap:url/image:image)"/>] images.
					</div>
					<table class="fancy-table">
						<thead>
							<tr>
								<th>Image Location</th>
								<th>Title</th>
							</tr>
						</thead>
						<tbody>
							<xsl:for-each select="sitemap:urlset/sitemap:url/image:image">
								<xsl:variable name="location">
									<xsl:value-of select="image:loc"/>
								</xsl:variable>
								<tr>
									<td><a href="{$location}" class="sitemap-link"><xsl:value-of select="image:loc"/></a></td>
									<td><xsl:value-of select="image:title"/></td>
								</tr>
							</xsl:for-each>
						</tbody>
					</table>
				</xsl:if>
			</div>
		</div>
	</body>
</html>
	</xsl:template>
</xsl:stylesheet>
